# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x05stats\"\x18\n\x08PlayerId\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x18\n\x08\x41uthCode\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\xbf\x01\n\x0c\x41uthResponse\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.stats.AuthResponse.Type\x12/\n\x06player\x18\x02 \x01(\x0b\x32\x1a.stats.AuthResponse.PlayerH\x00\x88\x01\x01\x1a$\n\x06Player\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"%\n\x04Type\x12\x0b\n\x07success\x10\x00\x12\x10\n\x0cunauthorized\x10\x01\x42\t\n\x07_player\"_\n\x0eUnlinkResponse\x12(\n\x04type\x18\x01 \x01(\x0e\x32\x1a.stats.UnlinkResponse.Type\"#\n\x04Type\x12\x0b\n\x07success\x10\x00\x12\x0e\n\nnot_linked\x10\x01\x32p\n\x04\x41uth\x12\x32\n\x06unlink\x12\x0f.stats.PlayerId\x1a\x15.stats.UnlinkResponse\"\x00\x12\x34\n\nacceptCode\x12\x0f.stats.AuthCode\x1a\x13.stats.AuthResponse\"\x00\x42/\n\x19ru.skykatik.tgintegr.grpcB\x10PlayersAuthProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031ru.skykatik.tgintegr.grpcB\020PlayersAuthProtoP\001'
  _globals['_PLAYERID']._serialized_start=21
  _globals['_PLAYERID']._serialized_end=45
  _globals['_AUTHCODE']._serialized_start=47
  _globals['_AUTHCODE']._serialized_end=71
  _globals['_AUTHRESPONSE']._serialized_start=74
  _globals['_AUTHRESPONSE']._serialized_end=265
  _globals['_AUTHRESPONSE_PLAYER']._serialized_start=179
  _globals['_AUTHRESPONSE_PLAYER']._serialized_end=215
  _globals['_AUTHRESPONSE_TYPE']._serialized_start=217
  _globals['_AUTHRESPONSE_TYPE']._serialized_end=254
  _globals['_UNLINKRESPONSE']._serialized_start=267
  _globals['_UNLINKRESPONSE']._serialized_end=362
  _globals['_UNLINKRESPONSE_TYPE']._serialized_start=327
  _globals['_UNLINKRESPONSE_TYPE']._serialized_end=362
  _globals['_AUTH']._serialized_start=364
  _globals['_AUTH']._serialized_end=476
# @@protoc_insertion_point(module_scope)
